export let resultadosGenerales = {
    range: 'Sheet1!A1:CJ787',
    majorDimension: 'ROWS',
    values: [
        [
            'timestamp',
            'departamento',
            'antiguedad',
            'edad',
            'gpo1-preg1',
            'gpo1-preg2',
            'gpo1-preg3',
            'gpo1-preg4',
            'gpo1-preg5',
            'gpo2-preg1',
            'gpo2-preg2',
            'gpo2-preg3',
            'gpo2-preg4',
            'gpo2-preg5',
            'gpo2-preg6',
            'gpo2-preg7',
            'gpo3-preg1',
            'gpo3-preg2',
            'gpo3-preg3',
            'gpo3-preg4',
            'gpo3-preg5',
            'gpo3-preg6',
            'gpo3-preg7',
            'gpo3-preg8',
            'gpo3-preg9',
            'gpo3-preg10',
            'gpo3-preg11',
            'gpo3-preg12',
            'gpo3-preg13',
            'gpo3-preg14',
            'gpo3-preg15',
            'gpo3-preg16',
            'gpo4-preg1',
            'gpo4-preg2',
            'gpo4-preg3',
            'gpo4-preg4',
            'gpo5-preg1',
            'gpo5-preg2',
            'gpo5-preg3',
            'gpo5-preg4',
            'gpo5-preg5',
            'gpo5-preg6',
            'gpo5-preg7',
            'gpo6-preg1',
            'gpo6-preg2',
            'gpo6-preg3',
            'gpo6-preg4',
            'gpo6-preg5',
            'gpo6-preg6',
            'gpo7-preg1',
            'gpo7-preg2',
            'gpo7-preg3',
            'gpo7-preg4',
            'gpo7-preg5',
            'gpo7-preg6',
            'gpo7-preg7',
            'gpo7-preg8',
            'gpo7-preg9',
            'gpo7-preg10',
            'gpo7-preg11',
            'gpo7-preg12',
            'gpo8-preg1',
            'gpo8-preg2',
            'gpo8-preg3',
            'gpo9-preg1',
            'gpo9-preg2',
            'gpo9-preg3',
            'gpo9-preg4',
            'gpo9-preg5',
            'gpo9-preg6',
            'gpo10-preg1',
            'gpo10-preg2',
            'gpo10-preg3',
            'gpo10-preg4',
            'gpo11-preg1',
            'gpo11-preg2',
            'gpo11-preg3',
            'gpo11-preg4',
            'gpo11-preg5',
            'gpo12-preg1',
            'gpo12-preg2',
            'gpo12-preg3',
            'gpo13-preg1',
            'gpo13-preg2',
            'gpo13-preg3',
            'gpo13-preg4',
            'gpo13-preg5',
            'gpo13-preg6'
        ],
        [
            '3/10/2020',
            'POSTVENTA OPERATIVA (TECNICOS)',
            '0 a 5 años',
            '20 a 25 años',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Atención a las demás sucursales , fomentar el trabajo en equipo , la humildad .',
            'Retroalimentaría la humildad , la comunicación y el trabajo en equipo.\r\nTomaría más en cuenta las otras sucursales pues también aportan mucho a la empresa .',
            'Que tomará en cuenta las opiniones que le damos más a fondo pues no hay un buen control con la coordinación.',
            'Con mis compañeros MobileMe y de taller siempre ha sido un buen ambiente laboral y les deseo lo mejor pues me han apoyado mucho ...\r\nPero  a la parte administrativa (coordinación) en especifico sería que fuera mas entregada y humilde pues tanto ella necesita de nosotros como nosotros de ella .',
            'Crecer , darnos a conocer con resultados y respeto compañerismo comunicación ',
            'En sucursal silao no hay una buena organización en el tema (móviles) pues su coordinación no sabe sobre el rango o el tema de los montacargas y eso nos perjudica mucho .'
        ],
        [
            '3/10/2020',
            'POSTVENTA OPERATIVA (TECNICOS)',
            '0 a 5 años',
            'Más de 41',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Me gustaría emprender una forma de trabajar en la que el técnico tuviera la oportunidad de poder sacar más ingresos y a su vez la empresa que obtenga sus ganancias correspondientes ',
            'Cambiaria la tabulación de sueldos para que se haga más atractivo el puesto de tecnico',
            'Preocuparse un poco más por los detalles que se quedan olvidados como las cotizaciones o la falta de refacciones',
            'La importancia de una buena atención hacia los clientes sobre todo el trato y el tiempo de atencion',
            'Misión.hacer que la empresa sea una empresa sustentable y sólida para nuestros clientes ytrabajadores. Visión.contar con los mejores productos en precio y calidad. Valores tratar a todos nuestros clientes con respeto y amabilidad al igual que a todo el personal',
            'Seria buenos tener una estabilidad económica buena para no tener que andar buscando otros trabajos y poder formar una antigüedad en la empresa'
        ],
        [
            '3/10/2020',
            'POSTVENTA OPERATIVA (TECNICOS)',
            'Más de 16',
            'Más de 41',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Desarrollar un plan de crecimiento de el personal no dejar que se hagan viejos en el mismo lugar fluir fluir fluir\r\nSer más selectivo el que no suma restarlo \r\nQue deje Dimosa de ser una escuela de líderes en otras empresas o trampolín \r\nlos mandos altos sin experiencia ser más rudo y exigente como ellos dicen si te opones que propones y encontrar los líderes que ocupa está empresa ',
            'Propiciar actividades para la EMPATÍA de el trabajo de todos promover la importancia de una buena integración de todos los departamentos para un Fin común que es recuperar la supremacia de ser el mejor distribuidor RAYMOND de la zona bajío ',
            'Ya existen los mecanismos \r\nBajar de dirección general los recursos para comVivir todos los compañeros en algún deporte  SUDAR EN EQUIPO comidas comer hombro con hombro aprender a escuchar  SIN PREJUICIO ',
            'La vida por si solo a ya es complicada o sabemos cuanto tiempo estaremos en este mundo \r\nQuitémonos de pendejadas de criticas envidias pretextos culpar al otro por nuestras decisiones y abrasemos a esta grupo de personas que son parte de nuestras vidas si no las quieren aprendan a quererlas\r\nSon parte de tu familia ',
            'SEGUIR SIENDO EL ENEMIGO A VENCER \r\nSeguir Marcano diferencias al solo escuchar la palabra llegó el técnico de DIMOSA \r\nSER LOS MEJORES DISTRIBUIDORES DE RAYMOND EN zona bajío y Guadalajara ',
            'Agradecimiento \r\nA toda la familia Dimosa por permitir directa o indirecta mente ser parte de su vida en estos años entrañables \r\nSeguir creciendo \r\nDios bendiga a Dimosa y a todos los miembros de esta familia '
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            '0 a 5 años',
            '20 a 25 años',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Invertir más en capacitar y reconocer a los elementos que de verdad están comprometidos con su trabajo y el bien de la empresa ',
            'Optimizar procesos ',
            'Que deje de ser tan lento y se concentre en las cosas más importantes por que pierde bastante tiempo en cosa que otros pueden atender además que deje de buscar la adulación y el protagonismo y la manipulación ',
            'Que tenemos que estar unidos para cumplir con las metas ',
            'Ser una empresa que desarrolla soluciones de equipos de logística para los clientes basados en la honestidad, el compromiso con la calidad y trabajando como una “familia”',
            'Ninguno'
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            '6 a 10 años',
            '26 a 30 años',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Principalmente detectar a la gente que está conmigo para trabajar en los grandes proyectos con ellos y hacer juntos los planes de negocios con motivación y no con miedo, y darles a ellos sus herramientas de trabajo, y ya después que se tenga un avance, ahora sí poder invertir en naves y stock de montacargas, preguntar qué es lo que quieren y no lo que yo imagino que quieren, así como involucrarme en mi empresa y con mis empleados.',
            'Cambiaría a la gente Tóxica, posteriormente daría las herramientas de trabajo al personal que lo requiere , valore y necesita y que no me roba, y posteriormente invertiría en comprar montacargas para tenerlos en stock',
            'Valore más a la empresa , dejando de prostituirla con empleados que no les gusta trabajar aquí y  que sólo la ocupan como empresa de paso y poner más atención a las áreas y personas que dejan más beneficios monetarios y laborales a la misma',
            'Que le presten más importancia a su área laboral y menos a las demás áreas , dejando la envidia y siendo más maduros , separand lo laboral  de lo persnal',
            'Nuestra visión es lo que tenemos en mente y deseos de querer ser, ejemplo: la empresa líder en venta, renta, reparación de montacargas .\r\nNuestra misión: Es hacer todo lo que está en. U estarás manos para lograrlo, mediante nuestros valore.',
            'Quisiera que tomaran en cuenta la lealtad de la gente que verdaderamente quiere estar aquí, ya que es a la que más nos juzgan y menos nos dan, que valoren a la gente que no roba y no habla mal de la empresa y de los jefes , ya que se les a demostrado que cuentan con nosotro, y deje de hacer preferencias con los empleados'
        ],
        [
            '3/10/2020',
            'POSTVENTA OPERATIVA (TECNICOS)',
            'Más de 16',
            'Más de 41',
            'Algunas veces sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            '1. al personal de cada aria asignarle bien sus tareas y hacerlos responsables.\r\n2. tener una organización para reducir tiempos de trabajo, facturacion solicitud de refacciones y cotizaciones .\r\n3. investigar el mercado precios servicios y deficiencias de la competencia,\r\n4. incrementar mas herramienta en taller para hacernos auto suficientes y recortar los tiempos de entrega.\r\n5. Empesar a separar arias, para darnos cuenta y poder ver que área es la que se tiene que apoyar.',
            'tomar en cuenta el personal que realiza bien su trabajo para poder competir con la competencia.\r\nconsiderar mas arias de oportunidades paratodos.\r\nrealizar un esquema de mejora continua.\r\ny poner al personal adecuado en cada aria.',
            'que no fuera tan elitista, yno pensara en su beneficio personal.',
            'que es importante realizar bien nuestro trabajo, aunque en ocaciones tu jefe inmediato   no te reconozca , y no le den el valor que uno espera.',
            'ser el numero 1. e nel mercado.\r\nser reconocidos.\r\nseguir avanzando.\r\nseguir siendo una familia.',
            'seria importante que frecuentaran las arias en general todas y evaluar, para que se den cuenta de las deficiencias que tenemos, y ver si el personal es apto para desarrollar el puesto al que este a cargo, ya que esto entorpece procesos y crecimiento de la empresa. y por consecuente a uno.'
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            '0 a 5 años',
            '20 a 25 años',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Quitar las personas que hacen un pésimo ambiente de trabajo, personas conflictivas.',
            'Los compañeros creo qué hay pésimo, ambiente laboral por parte de un compañero que solo se la vive criticando a los demás creo que le hace falta trabajar más.',
            'La verdad es un excelente jefe, que siga así con esa relación que tiene  con nosotros,que siempre nos fomente buenos hábitos laborales, que siempre siga así.',
            'Que se pongan a trabajar y que dejen sus niñerías, sus pésimos comentarios, que si les molestan algo de uno que se los digan en su cara que se den de sus niñerías de que lo anden divulgando ante los demás yo digo que los problemas personales se quedan afuera y los problemas laborales se resuelven aquí, aquí venimos a trabajar en equipo que si te caigo mal está bien pero no involucremos lo personal con lo laboral.',
            'No me acuerdo ',
            'La verdad Dimosa es una excelente compañía para poder crecer profesionalmente y creo que nos da buenas  oportunidades.'
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            '0 a 5 años',
            '20 a 25 años',
            'Nunca sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Darle más seguimiento a los clientes ',
            'Hiciera un manual donde pudiera ver los clientes y hacer una pagina para poder ofrecerles nuestros servicios ',
            'Que recomiende que salgan a buscar más clientes ',
            'Que no se metan tanto en la vida de los demás ',
            'Que todos trabajemos en equipo y tengamos responsabilidad y fidelidad',
            'Que también hubiera un manual de números d e parte detonas las refacciones y equipos '
        ],
        [
            '3/10/2020',
            'POSTVENTA OPERATIVA (TECNICOS)',
            '0 a 5 años',
            'Más de 41',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Visitaría más seguido mis sucursales y preguntaría a mi gerente cuántas empresas te han quitado y porque y cuántas has ganado si no has ganado porque que te falta para que eso suceda',
            'La forma de pensar de mi jefe inmediato de sentarse a esperar la respuesta del cliente cuando el cliente está esperando que yo acuda a su empresa y le ayude a mejorar su operación somos una empresa con mucha oportunidad en esta zona y nos estamos quedando atrás muy atras',
            'Ser la persona transparente y clara que dice ser para con los empleados y tratar de hacer crecerá la empresa de manera seria y contundente ya que creo que la empresa tiene mucha oportunidad de renta pero caminamos demasiado lento la empresa tiene equipo de calidad para sobresalir en ese campo creo que falta actitud de vender o rentarcre',
            'Seguir esforzándose y aprender del día a día ',
            'La misión creo yo ser la empresa número uno en la venta y renta de montacargas la vision tener el mayor número de empresas dando servicio de mantenimiento ventas y rentas a nivel nacional la ',
            'Creo a mi forma de pensar falta renumerar a los tecnicos por conocimientos en campo y actitud laborar ya que dependemos de la reparación de el montacargas y generalmente faltan refacciones y se retrasa la entrega del equipo y por lo tanto la forma de pago o de compensacion'
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            '0 a 5 años',
            '26 a 30 años',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Me gustaría reforzar el trabajo en equipo , para que las áreas sean armonía para que cada uno de los empleados disfrute estar en el lugar que están , y que en los pasillos no sean chismes si no que se escuche o contrario así sería más fácil llegar a cada uno de los objetivos .',
            'No haría cambios , aun que en personal que no se sintiera gusto en empresa tal vez ahí si tomaría decisiones pero por algo estamos aquí , ya es así mejor mejoraría para llevar a mi empresa por buen camino . ',
            'Mis recomendaciones serían las siguientes :\r\n\r\n1. Área de venta , exigir un poco más asesores para que puedan llegar a cumplir sus objetivos .\r\n\r\n2. Al momento de contratar personal nuevo , observar bien ha quien se le dará el sí .\r\n\r\n3. Involucrarse un poco más con personal no digo que lo lo hace pero a veces pasan situaciones desagradables que se dejan pasar pero llega un límite y por no querer angustiarlo lo dejamos pasar , pero estaría mejor que el lo pueda percibir y darse cuenta con qué tipo de personas está laborando .\r\n\r\n4. Que no deje de ser el jefe que es , es una persona con muchos valores , que sabe escucharte y apoyarte .',
            'Todos vamos en el mismo barco , si uno de nosotros llega a faltar ,el barco se desequilibraría , tomen en cuenta que somos un EQUIPO y que en vez de criticar a lo negativo todos nos ayudemos y aprendamos de nuestros errores . ',
            'Misión :\r\nEs una empresa que quieres llegar a cumplir sus objetivos y para ello tendría que llegar ha realizar un estudio de mercado , para dar a conocer sus productos .\r\n\r\nVisión:\r\nLograr ser una empresa de primer mundo en el nivel de maquinaria innovadora dar a conocer su marca y llegar hacer una empresa reconocida .\r\n\r\nValores :\r\n\r\nResponsabilidad , humanismo , respeto , tolerancia , honestidad , liderazgo .',
            'En mi departamento me gustaría compartir que se realice como en GDL, que los asesores realicen sus actividades como salir a prospectar ya que no salen de oficina y puedan a llegar a tener más oportunidad de ventas y rentas para cumplir sus objetivos . Al igual si yo estoy realizando mis actividades mal no estaría mal que nos retroalimentaran para ir mejorando cada día .'
        ],
        [
            '3/10/2020',
            'COMERCIAL / VENTAS',
            'Más de 16',
            'Más de 41',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Algunas veces sucede',
            'Con frecuencia sucede',
            'Siempre sucede',
            'Siempre sucede',
            'Con frecuencia sucede',
            'Con frecuencia sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Nunca sucede',
            'Mayor presencia de Capital Humano. No para solo auditar sino para sumarse y tomar también la responsabilidad del Recurso Humano en su búsqueda de realización que al final buscan conseguir en una compañía con la cual se identifiquen. ',
            'Mayor inversión en capital humano. Con el personal enfocado todo es posible. No hay objetivo ni meta inalcanzable. ',
            'Mayor comunicación y confianza ',
            'Poner todos de nuestra parte, sumarse, no hay compañía que tenga malas intenciones, ni líderes, al final todos buscamos lo mismo,  nosotros  podemos convertir a la compañia con nuestro grano de arena en un mejor lugar de trabajo. No es buscar afuera lo que somos incapaces de hacer donde nos encontramos. La responsabilidad es conjunta. Empresa y colaborador.  ',
            'Nuestro marco filosófico  lo resumiría en Ser un elemento de apoyo integral a las compañías en su operación logística cuya visión de Ser líder en el manejo de materiales de la industria se vea sustentado a través de un sentido humano en los valores de honestidad, responsabilidad y etica. ',
            'Buscar elementos de apoyo que nos ayuden a integrar al recurso humano y enfocarlo a los objetivos. No hay personas malas, es crecer Y estar dispuestos todos a aprender para tener la capacidad como empresa de dar curso a requerimientos muchas veces intangibles. '
        ]
    ]
};
